# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

"""Atomic staging → repo promote."""

from __future__ import annotations

import logging
import shutil
from pathlib import Path

logger = logging.getLogger(__name__)


class PromoteError(Exception):
    pass


# The staging gate imports the package and runs its tests in place, so staging
# holds build caches by the time we promote. They are not generated output.
_STAGING_ARTIFACTS = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache")


def _prepare_promoting(src: Path, dest: Path) -> Path:
    """Copy ``src`` to ``dest.promoting`` (overwriting any stale sibling)."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    promoting = dest.with_name(dest.name + ".promoting")
    if promoting.exists():
        shutil.rmtree(promoting)
    shutil.copytree(src, promoting, ignore=_STAGING_ARTIFACTS)
    return promoting


def _backup_if_exists(dest: Path) -> Path | None:
    if not dest.exists():
        return None
    backup = dest.with_name(dest.name + ".bak")
    if backup.exists():
        shutil.rmtree(backup)
    dest.rename(backup)
    return backup


def _restore_backup(backup: Path | None, dest: Path) -> None:
    if backup is None or not backup.exists():
        return
    if dest.exists():
        shutil.rmtree(dest)
    backup.rename(dest)


def _cleanup_backup(backup: Path | None) -> None:
    if backup is not None and backup.exists():
        shutil.rmtree(backup)


_GENERATED_MARKER = "Generated by nw-connector-builder"


def assert_generator_owned(node_wire_root: Path, connector_id: str) -> None:
    """Refuse to overwrite a connector package this tool did not write.

    ``--force`` means "replace the connector I generated last time", not "delete
    the hand-written connector that happens to share this id". Building with an
    id like ``slack`` would otherwise replace ``src/node_wire_slack/`` wholesale —
    and the generated package's ``declare_secret_shape`` call would then replace
    that connector's tenant-secret contract too, so stored credentials stop
    validating. Deliberately not overridable by a flag: deleting hand-written
    source should be an explicit act, not a side effect of a build.

    Called twice by design — once up front by the pipeline, because the staging
    gate imports the generated module (which runs its ``declare_secret_shape``)
    long before promote would get a say, and once here as the last line of
    defence for any caller that reaches promote directly.
    """
    src_dest = node_wire_root / "src" / f"node_wire_{connector_id}"
    logic = src_dest / "logic.py"
    if not logic.is_file():
        return
    try:
        head = logic.read_text(encoding="utf-8")[:512]
    except OSError:
        return
    if _GENERATED_MARKER in head:
        return
    raise PromoteError(
        f"{src_dest} exists and was not written by nw-connector-builder — refusing to "
        f"overwrite a hand-written connector. Pick a different --id (e.g. "
        f"{connector_id}_api), or move the existing package aside first."
    )


def promote(
    staging: Path,
    node_wire_root: Path,
    connector_id: str,
    *,
    force: bool,
) -> None:
    """Promote both trees with a two-phase commit and cross-tree rollback.

    1. Copy both staging trees to ``*.promoting`` siblings (no dest mutation yet).
    2. Move existing destinations aside to ``*.bak`` (if any).
    3. Rename both ``*.promoting`` → final destinations.
    4. On failure after step 2/3 starts, restore both backups and discard promoting.
    """
    src_dest = node_wire_root / "src" / f"node_wire_{connector_id}"
    pkg_dest = node_wire_root / "packages" / "connectors" / connector_id
    src_stage = staging / "src" / f"node_wire_{connector_id}"
    pkg_stage = staging / "packages" / "connectors" / connector_id

    assert_generator_owned(node_wire_root, connector_id)

    if (src_dest.exists() or pkg_dest.exists()) and not force:
        raise PromoteError(f"Destination already exists for {connector_id!r}; re-run with --force")

    src_promoting = _prepare_promoting(src_stage, src_dest)
    pkg_promoting = _prepare_promoting(pkg_stage, pkg_dest)

    # (backup_path | None, destination) — built incrementally so a mid-backup
    # failure still restores whatever was already moved aside.
    backups: list[tuple[Path | None, Path]] = []
    try:
        backups.append((_backup_if_exists(src_dest), src_dest))
        backups.append((_backup_if_exists(pkg_dest), pkg_dest))

        src_promoting.rename(src_dest)
        try:
            pkg_promoting.rename(pkg_dest)
        except Exception:
            # Undo src rename; outer handler restores *.bak trees.
            if src_dest.exists():
                shutil.rmtree(src_dest)
            raise

        for backup, _ in backups:
            _cleanup_backup(backup)
    except Exception:
        if src_promoting.exists():
            shutil.rmtree(src_promoting, ignore_errors=True)
        if pkg_promoting.exists():
            shutil.rmtree(pkg_promoting, ignore_errors=True)
        # After successful cleanup above, backup dirs are already gone.
        for backup, dest in backups:
            _restore_backup(backup, dest)
        raise

    logger.info("Promoted connector %s", connector_id)
