# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

"""Source fragments for node-wire mode: tool argument dicts and the generated client module."""

from __future__ import annotations

from typing import Dict, List

from mcp_builder.generate.plan import ParamPlan, ServerPlan
from mcp_builder.generate.renderers.escape import escape_python_string
from nw_stacklok.resolve import BODY_PREFIX


def arguments_expr(params: List[ParamPlan]) -> str:
    """Python dict literal mapping connector input fields to the tool's arguments.

    Flattened body properties bind to their own field; a whole-body action gets one ``body``
    dict built from the scoped body parameters.
    """
    pairs: List[str] = []
    body: Dict[str, str] = {}
    for p in params:
        target = p.nw_field or p.py_name
        if target.startswith(BODY_PREFIX):
            body[target[len(BODY_PREFIX) :]] = p.py_name
        else:
            pairs.append(f'"{escape_python_string(target)}": {p.py_name}')
    if body:
        inner = ", ".join(f'"{escape_python_string(k)}": {v}' for k, v in body.items())
        pairs.append(f'"body": {{{inner}}}')
    return "{" + ", ".join(pairs) + "}"


_CLIENT_TEMPLATE = '''"""node-wire client for the {server_name} MCP server.

Generated by nw-stacklok-builder: tools run through the node-wire connector
``{connector_id}`` (node-wire runtime) instead of calling the upstream API directly.
ToolHive's forwarded credential and tenant header are read per request by
node_wire_toolhive.NodeWireClient.
"""

import os
from pathlib import Path
from typing import Any

from node_wire_toolhive import NodeWireClient

CONNECTOR_ID = "{connector_id}"


def _config_path() -> Path:
    configured = os.environ.get("NW_CONFIG_PATH", "").strip()
    if configured:
        return Path(configured)
    # src/<module>/client.py → project root
    return Path(__file__).resolve().parents[2] / "config" / "connectors.yaml"


_NODE_WIRE = NodeWireClient(CONNECTOR_ID, config_path=_config_path())


class APIClient:
    """Runs node-wire connector actions for the generated tools."""

    def __init__(self) -> None:
        self.node_wire = _NODE_WIRE

    async def run(self, action: str, arguments: dict[str, Any]) -> Any:
        return await self.node_wire.run(action, arguments)
'''


def client_module(plan: ServerPlan) -> str:
    """The generated ``client.py`` for node-wire mode (replaces stacklok's httpx client)."""
    assert plan.node_wire is not None
    return _CLIENT_TEMPLATE.format(
        server_name=plan.server_name, connector_id=plan.node_wire.connector_id
    )
