# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

"""scripts/reset_connector.py against a throwaway git repo."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "reset_connector.py"
MARKER = '"""Generated by nw-connector-builder."""\n'

CONNECTORS_YAML = """\
# Connector registry
connectors:
  slack:
    enabled: true
  slack_web:  # committed wiring stays
    enabled: true
    auth:
      secret_key: SLACK_WEB_ACCESS_TOKEN
"""
SAMPLE_ENV = "NW_ALLOWED_CONNECTORS=slack,slack_web\nSLACK_WEB_ACCESS_TOKEN=\n"
BUILD_PACKAGES = "ALL_PACKAGES=(\n  packages/runtime\n  packages/connectors/slack\n)\n"


def _git(root: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=root, check=True, capture_output=True)


def _write(path: Path, text: str = "") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


@pytest.fixture
def root(tmp_path: Path) -> Path:
    root = tmp_path / "node-wire"
    _write(root / "config" / "connectors.yaml", CONNECTORS_YAML)
    _write(root / "sample.env", SAMPLE_ENV)
    _write(root / "scripts" / "build-packages.sh", BUILD_PACKAGES)
    _write(root / "src" / "node_wire_slack" / "logic.py", "# hand-written\n")
    _write(root / "nw-stacklok-builder" / "scoping" / "slack_web" / "mcp-scope.yaml", "x: 1\n")
    _git(root, "init", "-q")
    _git(root, "add", ".")
    _git(root, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "base")
    return root


def _generate(root: Path, connector_id: str, server: str) -> None:
    """What gen-all + gen-stacklok leave behind for ``connector_id`` (untracked)."""
    hyphen = connector_id.replace("_", "-")
    _write(root / "src" / f"node_wire_{connector_id}" / "logic.py", MARKER)
    _write(root / "src" / f"node_wire_{connector_id}.egg-info" / "PKG-INFO")
    _write(root / "packages" / "connectors" / connector_id / "dist" / "x.whl")
    _write(root / "nw-mcp-builder" / "out" / f"{hyphen}-nw-mcp" / "Dockerfile")
    _write(
        root / "nw-stacklok-builder" / "out" / f"{server}-mcp" / "config" / "connectors.yaml",
        f"connectors:\n  {connector_id}: {{}}\n",
    )
    _write(root / "nw-stacklok-builder" / "scoping" / connector_id / "analyze.json", "{}")
    _write(root / "nw-stacklok-builder" / "specs" / f"{connector_id}.openapi.json", "{}")


def _run(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args, "--root", str(root)],
        capture_output=True,
        text=True,
        stdin=subprocess.DEVNULL,
    )


def test_removes_generated_files_and_uncommitted_wiring_only(root: Path) -> None:
    _generate(root, "pet_store", "petstore")
    _generate(root, "slack_web", "slack-web")
    _write(
        root / "nw-stacklok-builder" / "out" / "other-mcp" / "config" / "connectors.yaml",
        "connectors:\n  other: {}\n",
    )
    # gen-all's wiring for pet_store, on top of the committed files.
    (root / "config" / "connectors.yaml").write_text(
        CONNECTORS_YAML
        + "  pet_store:\n    auth:\n      secret_key: PET_STORE_API_KEY\n"
        + "    auth_schemes:\n      petstore_auth:\n        secret_key: PET_STORE_ACCESS_TOKEN\n",
        encoding="utf-8",
    )
    (root / "sample.env").write_text(
        "NW_ALLOWED_CONNECTORS=slack,slack_web,pet_store\nSLACK_WEB_ACCESS_TOKEN=\n"
        "PET_STORE_API_KEY=\n# PET_STORE_ACCESS_TOKEN: host-supplied credential — ...\n"
        "PET_STORE_ACCESS_TOKEN=\n",
        encoding="utf-8",
    )
    (root / "scripts" / "build-packages.sh").write_text(
        BUILD_PACKAGES.replace(")\n", "  packages/connectors/pet_store\n)\n"), encoding="utf-8"
    )

    result = _run(root, "pet_store", "slack_web", "--yes")

    assert result.returncode == 0, result.stderr
    for gone in (
        "src/node_wire_pet_store",
        "src/node_wire_pet_store.egg-info",
        "packages/connectors/pet_store",
        "nw-mcp-builder/out/pet-store-nw-mcp",
        "nw-stacklok-builder/out/petstore-mcp",
        "nw-stacklok-builder/out/slack-web-mcp",
        "nw-stacklok-builder/scoping/slack_web",
        "nw-stacklok-builder/specs/slack_web.openapi.json",
    ):
        assert not (root / gone).exists(), gone
    assert (root / "nw-stacklok-builder" / "out" / "other-mcp").is_dir()
    assert (root / "src" / "node_wire_slack" / "logic.py").is_file()
    # Uncommitted wiring is undone; committed wiring (slack_web) and comments stay.
    assert (root / "config" / "connectors.yaml").read_text(encoding="utf-8") == CONNECTORS_YAML
    assert (root / "sample.env").read_text(encoding="utf-8") == SAMPLE_ENV
    assert (root / "scripts" / "build-packages.sh").read_text(encoding="utf-8") == BUILD_PACKAGES
    assert "mcp-scope.yaml is tracked by git" in result.stdout


def test_dry_run_removes_nothing(root: Path) -> None:
    _generate(root, "pet_store", "petstore")
    result = _run(root, "pet_store", "--dry-run")
    assert result.returncode == 0, result.stderr
    assert f"remove  {Path('src/node_wire_pet_store')}" in result.stdout
    assert (root / "src" / "node_wire_pet_store").is_dir()


def test_refuses_hand_written_connector(root: Path) -> None:
    result = _run(root, "slack", "--yes")
    assert result.returncode == 1
    assert "hand-written connector" in result.stderr
    assert (root / "src" / "node_wire_slack" / "logic.py").is_file()


def test_refuses_git_tracked_connector_package(root: Path) -> None:
    _write(root / "packages" / "connectors" / "tracked" / "pyproject.toml")
    _git(root, "add", ".")
    _git(root, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "tracked")
    result = _run(root, "tracked", "--yes")
    assert result.returncode == 1
    assert "tracked by git" in result.stderr


def test_asks_before_removing_and_needs_yes_without_a_terminal(root: Path) -> None:
    _generate(root, "pet_store", "petstore")
    result = _run(root, "pet_store")
    assert result.returncode == 1
    assert "pass --yes" in result.stderr
    assert (root / "src" / "node_wire_pet_store").is_dir()


def test_rejects_invalid_ids(root: Path) -> None:
    result = _run(root, "../src", "--yes")
    assert result.returncode == 1
    assert "invalid connector id" in result.stderr


def test_unwires_every_connector_given(root: Path) -> None:
    for connector_id in ("pet_store", "ms_teams"):
        _generate(root, connector_id, connector_id.replace("_", "-"))
    (root / "config" / "connectors.yaml").write_text(
        CONNECTORS_YAML
        + "  pet_store:\n    auth:\n      secret_key: PET_STORE_API_KEY\n"
        + "  ms_teams:\n    auth:\n      secret_key: MS_TEAMS_ACCESS_TOKEN\n",
        encoding="utf-8",
    )
    (root / "sample.env").write_text(
        "NW_ALLOWED_CONNECTORS=slack,slack_web,pet_store,ms_teams\nSLACK_WEB_ACCESS_TOKEN=\n"
        "PET_STORE_API_KEY=\nMS_TEAMS_ACCESS_TOKEN=\n",
        encoding="utf-8",
    )
    (root / "scripts" / "build-packages.sh").write_text(
        BUILD_PACKAGES.replace(
            ")\n", "  packages/connectors/pet_store\n  packages/connectors/ms_teams\n)\n"
        ),
        encoding="utf-8",
    )

    result = _run(root, "pet_store", "ms_teams", "--yes")

    assert result.returncode == 0, result.stderr
    assert (root / "config" / "connectors.yaml").read_text(encoding="utf-8") == CONNECTORS_YAML
    assert (root / "sample.env").read_text(encoding="utf-8") == SAMPLE_ENV
    assert (root / "scripts" / "build-packages.sh").read_text(encoding="utf-8") == BUILD_PACKAGES
