# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

"""Fixtures: a node-wire Petstore connector built once, and scopes that run on it."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

import pytest
import yaml

from nw_connector_builder.pipeline import run_build

FIXTURES = Path(__file__).parent / "fixtures" / "stacklok"
TEMPLATE = Path(__file__).resolve().parents[2] / "nw-stacklok-builder" / "template"
PETSTORE_SPEC = FIXTURES / "petstore_openapi.json"
PETSTORE_BASE_URL = "https://petstore3.swagger.io/api/v3"
CONNECTOR_ID = "pet_store"


@dataclass(frozen=True)
class NodeWireCheckout:
    root: Path

    def scope(self, tmp_path: Path, **overrides: Any) -> Path:
        """Stacklok's Petstore scope plus a node-wire runtime block, written to ``tmp_path``."""
        scope: Dict[str, Any] = yaml.safe_load((FIXTURES / "petstore.yaml").read_text())
        scope["runtime"] = {"type": "node_wire", "connector_id": CONNECTOR_ID}
        scope.update(overrides)
        path = tmp_path / "petstore-scope.yaml"
        path.write_text(yaml.safe_dump(scope, sort_keys=False), encoding="utf-8")
        return path


@pytest.fixture(scope="module")
def node_wire_checkout(tmp_path_factory: pytest.TempPathFactory) -> NodeWireCheckout:
    """A minimal node-wire tree with the Petstore connector generated by nw-connector-builder."""
    root = tmp_path_factory.mktemp("node-wire")
    for sub in ("src", "packages/connectors", "config", "nw-mcp-builder"):
        (root / sub).mkdir(parents=True)
    (root / "pyproject.toml").write_text("[project]\nname='node-wire'\n", encoding="utf-8")
    (root / "config" / "connectors.yaml").write_text("connectors: {}\n", encoding="utf-8")
    (root / "sample.env").write_text("", encoding="utf-8")
    code = run_build(
        spec=str(PETSTORE_SPEC),
        connector_id=CONNECTOR_ID,
        node_wire_root=root,
        no_mcp=True,
        wire=True,
        base_url=PETSTORE_BASE_URL,
        report_path=root / "abort-report.json",
    )
    assert code == 0
    return NodeWireCheckout(root)
