# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

"""Emit staged connector dual layout from DeriveResult."""

from __future__ import annotations

import json
import logging
import re
import textwrap
from pathlib import Path
from typing import Any

from nw_connector_builder.derive.operations import ActionPlan, DeriveResult

logger = logging.getLogger(__name__)


def _py_type(hint: str, required: bool, default: Any) -> str:
    if hint in {"str", "int", "float", "bool"} or hint.startswith("list[") or hint.startswith("dict["):
        base = hint
    elif re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", hint):
        base = hint
    else:
        base = "Any"
    if not required and default is None:
        return f"{base} | None"
    return base


def _field_extra(plan_param) -> str:  # noqa: ANN001
    style = repr(plan_param.style) if plan_param.style is not None else "None"
    explode = repr(plan_param.explode) if plan_param.explode is not None else "None"
    media = (
        repr(plan_param.media_type) if plan_param.media_type is not None else "None"
    )
    return (
        "{"
        f'"nw_in": "{plan_param.location}", '
        f'"nw_wire_name": {plan_param.wire_name!r}, '
        f'"nw_style": {style}, '
        f'"nw_explode": {explode}, '
        f'"nw_media_type": {media}'
        "}"
    )


def generate_schema_module(connector_id: str, result: DeriveResult) -> str:
    """Hand-roll input envelopes; use Any/dict for complex body/output when needed."""
    lines: list[str] = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, Optional",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "from node_wire_runtime import RestResponseOutput",
        "",
        "",
    ]

    # Shared body/output placeholders as dict wrappers when schemas exist
    for action in result.actions:
        in_name = _pascal(action.name) + "Input"
        out_name = _pascal(action.name) + "Output"
        lines.append(f"class {in_name}(BaseModel):")
        lines.append(f'    model_config = ConfigDict(populate_by_name=True, extra="forbid")')
        lines.append(f'    action: Literal[{action.name!r}] = {action.name!r}')
        for p in action.params:
            typ = _py_type(p.python_type_hint, p.required, p.default)
            alias = ""
            if p.field_name != p.wire_name:
                alias = f", alias={p.wire_name!r}"
            default = "..."
            if not p.required:
                default = repr(p.default) if p.default is not None else "None"
            lines.append(
                f"    {p.field_name}: {typ} = Field("
                f"{default}{alias}, json_schema_extra={_field_extra(p)})"
            )
        if action.body_schema is not None:
            # Nested body as Any/dict for v1 robustness (datamodel-codegen optional)
            body_extra = {
                "nw_in": "body",
                "nw_wire_name": "body",
                "nw_style": None,
                "nw_explode": None,
                "nw_media_type": action.body_media_type or "application/json",
            }
            lines.append(
                f"    body: Any | None = Field("
                f"None, json_schema_extra={body_extra!r})"
            )
        if len(action.params) == 0 and action.body_schema is None:
            lines.append("    pass")
        lines.append("")
        lines.append("")

        if action.use_rest_response_output:
            lines.append(f"{out_name} = RestResponseOutput")
        else:
            lines.append(f"class {out_name}(BaseModel):")
            lines.append('    model_config = ConfigDict(extra="allow")')
            lines.append("    # OpenAPI success schema — permissive allow for nested props")
            lines.append("    pass")
        lines.append("")
        lines.append("")

    return "\n".join(lines)


def _pascal(snake: str) -> str:
    return "".join(p.capitalize() for p in snake.split("_") if p)


def generate_logic_module(connector_id: str, result: DeriveResult) -> str:
    class_name = _pascal(connector_id) + "Connector"
    imports_in = []
    imports_out = []
    for a in result.actions:
        imports_in.append(_pascal(a.name) + "Input")
        imports_out.append(_pascal(a.name) + "Output")

    lines = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "from typing import ClassVar, Type",
        "",
        "from pydantic import BaseModel",
        "",
        "from node_wire_runtime import RestConnector, RestResponseOutput, nw_action",
        "",
        "from .schema import (",
    ]
    for name in sorted(set(imports_in + imports_out)):
        lines.append(f"    {name},")
    lines += [
        ")",
        "",
        "",
        f"class {class_name}(RestConnector):",
        f'    """Generated OpenAPI connector ``{connector_id}``."""',
        "",
        f'    connector_id = "{connector_id}"',
        f'    default_base_url = "{result.default_base_url}"',
        "    output_model: ClassVar[Type[BaseModel]] = RestResponseOutput",
        "    _nw_abstract_base = False",
        "",
    ]

    for a in result.actions:
        in_name = _pascal(a.name) + "Input"
        out_name = _pascal(a.name) + "Output"
        auth_kw = "" if a.auth else ", auth=False"
        lines += [
            f'    @nw_action("{a.name}")',
            f"    async def {a.name}(self, params: {in_name}, *, trace_id: str) -> {out_name}:",
            f"        return await self.execute_rest(",
            f'            method="{a.method}",',
            f"            path_template={a.path!r},",
            f"            params=params,",
            f"            output_model={out_name},",
            f"            trace_id=trace_id{auth_kw},",
            f"        )",
            "",
        ]
    return "\n".join(lines)


def generate_init_module(connector_id: str) -> str:
    return textwrap.dedent(
        f'''\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0
        """node_wire_{connector_id} connector package."""
        '''
    )


def generate_registration_module() -> str:
    return textwrap.dedent(
        '''\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0
        """Optional ErrorMapper side-effects (none required for generated REST connectors)."""
        '''
    )


def generate_package_pyproject(connector_id: str) -> str:
    dist = connector_id.replace("_", "-")
    return textwrap.dedent(
        f'''\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0

        [project]
        name = "node-wire-{dist}"
        version = "1.0.0"
        description = "Node Wire connector — {connector_id} (OpenAPI-generated)"
        requires-python = ">=3.11"
        license = "Apache-2.0"
        authors = [{{ name = "AOT Technologies", email = "opensource@aot-technologies.com" }}]

        dependencies = [
            "node-wire-runtime>=1.0.0",
            "httpx[http2]>=0.27.0,<0.28.0",
        ]

        [project.optional-dependencies]
        test = [
            "pytest>=8.0.0",
            "polyfactory>=2.16.0",
        ]

        [project.entry-points."node_wire.connectors"]
        {connector_id} = "node_wire_{connector_id}.logic"

        [build-system]
        requires = ["setuptools>=69.0.0", "cython>=3.0", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        where = ["../../../src"]
        include = ["node_wire_{connector_id}*"]

        [tool.pytest.ini_options]
        testpaths = ["tests"]
        '''
    )


def generate_model_tests(connector_id: str, result: DeriveResult) -> str:
    lines = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "import json",
        "",
        "from polyfactory.factories.pydantic_factory import ModelFactory",
        "",
        f"from node_wire_{connector_id} import schema as sch",
        "",
    ]
    for a in result.actions:
        in_name = _pascal(a.name) + "Input"
        lines += [
            f"def test_{a.name}_input_roundtrip() -> None:",
            f"    class _F(ModelFactory):",
            f"        __model__ = sch.{in_name}",
            f"    inst = _F.build()",
            f"    data = inst.model_dump(by_alias=True)",
            f"    again = sch.{in_name}.model_validate(data)",
            f"    assert again.action == {a.name!r}",
            "",
        ]
        if a.examples.get("request") is not None:
            lines += [
                f"def test_{a.name}_example_parses() -> None:",
                f"    example = {json.dumps(a.examples['request'])}",
                f"    payload = {{'action': {a.name!r}, 'body': example}}",
                f"    sch.{in_name}.model_validate(payload)",
                "",
            ]
    return "\n".join(lines)


def write_staging(
    staging: Path,
    connector_id: str,
    result: DeriveResult,
    report: dict[str, Any],
) -> None:
    src_pkg = staging / "src" / f"node_wire_{connector_id}"
    pkg = staging / "packages" / "connectors" / connector_id
    tests = pkg / "tests"
    fixtures = tests / "fixtures"
    src_pkg.mkdir(parents=True, exist_ok=True)
    tests.mkdir(parents=True, exist_ok=True)
    fixtures.mkdir(parents=True, exist_ok=True)

    (src_pkg / "__init__.py").write_text(generate_init_module(connector_id), encoding="utf-8")
    (src_pkg / "schema.py").write_text(
        generate_schema_module(connector_id, result), encoding="utf-8"
    )
    (src_pkg / "logic.py").write_text(
        generate_logic_module(connector_id, result), encoding="utf-8"
    )
    (src_pkg / "registration.py").write_text(generate_registration_module(), encoding="utf-8")
    (pkg / "pyproject.toml").write_text(
        generate_package_pyproject(connector_id), encoding="utf-8"
    )
    (tests / f"test_{connector_id}_models.py").write_text(
        generate_model_tests(connector_id, result), encoding="utf-8"
    )
    (tests / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    logger.info("Wrote staging tree under %s", staging)
