# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

# REUSE-IgnoreStart
# String literals below emit SPDX headers into generated files; ignore them here.

"""Emit staged connector dual layout from DeriveResult."""

from __future__ import annotations

import json
import logging
import re
import textwrap
from pathlib import Path
from typing import Any

from nw_connector_builder.derive.operations import DeriveResult

logger = logging.getLogger(__name__)

# Every value interpolated into generated Python/TOML source must either be
# constrained to this safe character set or passed through repr()/an escaper
# first — never spliced raw into a string literal. connector_id also becomes
# a Python identifier fragment (class/module names), so this is required for
# correctness, not just safety.
_CONNECTOR_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_connector_id(connector_id: str) -> None:
    if not _CONNECTOR_ID_RE.fullmatch(connector_id):
        raise ValueError(
            f"invalid connector_id {connector_id!r}: must match {_CONNECTOR_ID_RE.pattern!r}"
        )


def _py_type(hint: str, required: bool, default: Any) -> str:
    if (
        hint in {"str", "int", "float", "bool"}
        or hint.startswith("list[")
        or hint.startswith("dict[")
    ):
        base = hint
    else:
        # Unresolved / unknown names → Any (never emit dangling class refs).
        base = "Any"
    if not required and default is None:
        return f"{base} | None"
    return base


def _field_extra(plan_param) -> str:  # noqa: ANN001
    style = repr(plan_param.style) if plan_param.style is not None else "None"
    explode = repr(plan_param.explode) if plan_param.explode is not None else "None"
    media = repr(plan_param.media_type) if plan_param.media_type is not None else "None"
    return (
        "{"
        f'"nw_in": {plan_param.location!r}, '
        f'"nw_wire_name": {plan_param.wire_name!r}, '
        f'"nw_style": {style}, '
        f'"nw_explode": {explode}, '
        f'"nw_media_type": {media}'
        "}"
    )


def _example_placeholder(param) -> Any:  # noqa: ANN001
    if param.default is not None:
        return param.default
    hint = param.python_type_hint
    if hint == "int":
        return 1
    if hint == "bool":
        return True
    if hint == "float":
        return 1.0
    if hint.startswith("list["):
        return []
    if hint.startswith("dict["):
        return {}
    return "example"


def generate_schema_module(connector_id: str, result: DeriveResult) -> str:
    """Hand-roll input envelopes; use Any/dict for complex body/output when needed."""
    _validate_connector_id(connector_id)
    lines: list[str] = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "from node_wire_runtime import RestResponseOutput",
        "",
        "",
    ]

    # Shared body/output placeholders as dict wrappers when schemas exist
    for action in result.actions:
        in_name = _pascal(action.name) + "Input"
        out_name = _pascal(action.name) + "Output"
        lines.append(f"class {in_name}(BaseModel):")
        lines.append('    model_config = ConfigDict(populate_by_name=True, extra="forbid")')
        lines.append(f"    action: Literal[{action.name!r}] = {action.name!r}")
        for p in action.params:
            typ = _py_type(p.python_type_hint, p.required, p.default)
            alias = ""
            if p.field_name != p.wire_name:
                alias = f", alias={p.wire_name!r}"
            default = "..."
            if not p.required:
                default = repr(p.default) if p.default is not None else "None"
            lines.append(
                f"    {p.field_name}: {typ} = Field("
                f"{default}{alias}, json_schema_extra={_field_extra(p)})"
            )
        if action.body_schema is not None:
            # dict[str, Any] (not bare Any) so MCP inputSchema is a valid object
            # schema — Pydantic emits anyOf[{}, null] for Any, which clients reject.
            body_extra = {
                "nw_in": "body",
                "nw_wire_name": "body",
                "nw_style": None,
                "nw_explode": None,
                "nw_media_type": action.body_media_type or "application/json",
            }
            lines.append(
                f"    body: dict[str, Any] | None = Field(None, json_schema_extra={body_extra!r})"
            )
        if len(action.params) == 0 and action.body_schema is None:
            lines.append("    pass")
        lines.append("")
        lines.append("")

        if action.use_rest_response_output:
            lines.append(f"{out_name} = RestResponseOutput")
        else:
            # Object-shaped success schema only (see _success_response_schema).
            lines.append(f"class {out_name}(BaseModel):")
            lines.append('    model_config = ConfigDict(extra="allow")')
            lines.append("    # OpenAPI object success schema — permissive allow for nested props")
            lines.append("    pass")
        lines.append("")
        lines.append("")

    return "\n".join(lines)


def _pascal(snake: str) -> str:
    return "".join(p.capitalize() for p in snake.split("_") if p)


def generate_logic_module(connector_id: str, result: DeriveResult) -> str:
    _validate_connector_id(connector_id)
    class_name = _pascal(connector_id) + "Connector"
    imports_in = []
    imports_out = []
    for a in result.actions:
        imports_in.append(_pascal(a.name) + "Input")
        imports_out.append(_pascal(a.name) + "Output")

    enveloped = any(a.envelope_ok_field for a in result.actions)
    runtime_imports = "RestConnector, RestResponseOutput, nw_action"
    if enveloped:
        runtime_imports = "RestConnector, RestEnvelopeError, RestResponseOutput, nw_action"

    lines = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "from typing import ClassVar, Dict, Tuple, Type",
        "",
        "import httpx",
        "from pydantic import BaseModel",
        "",
        f"from node_wire_runtime import {runtime_imports}",
        "from node_wire_runtime.models import ErrorCategory",
        "from node_wire_runtime.tenant_persistence import declare_secret_shape",
        "",
        "from .schema import (",
    ]
    for name in sorted(set(imports_in + imports_out)):
        lines.append(f"    {name},")
    lines += [
        ")",
        "",
        "",
        f"class {class_name}(RestConnector):",
        f'    """Generated OpenAPI connector ``{connector_id}``."""',
        "",
        f"    connector_id = {connector_id!r}",
        f"    default_base_url = {result.default_base_url!r}",
        "    output_model: ClassVar[Type[BaseModel]] = RestResponseOutput",
        "    _nw_abstract_base = False",
        "",
        "    # RestConnector.execute_rest raises these; without a mapping every one",
        "    # of them would default to FATAL and never retry (see execute_rest in",
        "    # node_wire_runtime/rest.py). SsrfBlockedError is intentionally left",
        "    # unmapped for now.",
        "    error_map: ClassVar[Dict[Type[BaseException], Tuple[ErrorCategory, str]]] = {",
        '        httpx.TimeoutException: (ErrorCategory.RETRYABLE, "HTTP_TIMEOUT"),',
        '        httpx.ConnectError: (ErrorCategory.RETRYABLE, "HTTP_CONNECT_ERROR"),',
        '        httpx.ReadTimeout: (ErrorCategory.RETRYABLE, "HTTP_READ_TIMEOUT"),',
        '        httpx.RequestError: (ErrorCategory.FATAL, "HTTP_REQUEST_ERROR"),',
        '        httpx.HTTPStatusError: (ErrorCategory.BUSINESS, "HTTP_STATUS_ERROR"),',
    ]
    if enveloped:
        lines.append('        RestEnvelopeError: (ErrorCategory.BUSINESS, "API_ENVELOPE_ERROR"),')
    lines += [
        "    }",
        "",
    ]

    for a in result.actions:
        in_name = _pascal(a.name) + "Input"
        out_name = _pascal(a.name) + "Output"
        auth_kw = "" if a.auth else ", auth=False"
        decorator_kw = "" if a.auth else ", requires_auth=False"
        # auth_scheme_name is an OpenAPI securitySchemes key — always emit via !r.
        scheme_kw = f", auth_scheme={a.auth_scheme_name!r}" if a.auth_scheme_name else ""
        # The spec declares this response's success flag; a 2xx body reporting
        # failure must not read as a successful call.
        envelope_kw = f", envelope_ok_field={a.envelope_ok_field!r}" if a.envelope_ok_field else ""
        lines += [
            f'    @nw_action("{a.name}"{decorator_kw})',
            f"    async def {a.name}(self, params: {in_name}, *, trace_id: str) -> {out_name}:",
            "        return await self.execute_rest(",
            f'            method="{a.method}",',
            f"            path_template={a.path!r},",
            "            params=params,",
            f"            output_model={out_name},",
            f"            trace_id=trace_id{auth_kw}{scheme_kw}{envelope_kw},",
            "        )",
            "",
        ]

    lines += _secret_shape_lines(connector_id, result)
    return "\n".join(lines)


def _secret_shape_lines(connector_id: str, result: DeriveResult) -> list[str]:
    """Emit the ``declare_secret_shape`` call a generated connector needs at import time.

    The tenant secret store keeps a registry of which logical secrets each connector
    owns (``tenant_persistence.REQUIRED_SECRETS_BY_CONNECTOR`` and friends). Connectors
    that predate it are hard-coded there; anything generated has to declare itself or
    the config store refuses its credentials under ``NW_SECRET_SHAPE_POLICY=enforce``.

    The connector-level scheme's secrets are ``required`` — without them the connector
    cannot authenticate at all. Per-action scheme secrets are format-checked but not
    required, so a host can store the default credential without provisioning every
    optional scheme up front.
    """
    required = [k for k in result.auth_plan.secret_keys if k]
    formats = dict.fromkeys(required, "opaque_secret")
    for plan in result.extra_auth_plans.values():
        for key in plan.secret_keys:
            if key:
                formats.setdefault(key, "opaque_secret")

    lines = [
        "",
        "# Tenant-secret contract for the config store. Generated connectors are not in",
        "# the runtime's hard-coded registry, so they declare their own shape at import",
        "# time; without this the store rejects their credentials under",
        "# NW_SECRET_SHAPE_POLICY=enforce and stores them unvalidated under 'warn'.",
    ]
    if not formats:
        lines += [
            "# No auth scheme was derived — declared explicitly as 'no tenant secrets'.",
            f"declare_secret_shape({connector_id!r})",
        ]
        return lines

    lines.append("declare_secret_shape(")
    lines.append(f"    {connector_id!r},")
    if required:
        lines.append("    required=[")
        lines.extend(f"        {key!r}," for key in required)
        lines.append("    ],")
    lines.append("    formats={")
    lines.extend(f"        {key!r}: 'opaque_secret'," for key in formats)
    lines.append("    },")
    lines.append(")")
    return lines


def generate_init_module(connector_id: str) -> str:
    _validate_connector_id(connector_id)
    return textwrap.dedent(
        f'''\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0
        """node_wire_{connector_id} connector package."""
        '''
    )


def generate_package_pyproject(connector_id: str) -> str:
    _validate_connector_id(connector_id)
    dist = connector_id.replace("_", "-")
    return textwrap.dedent(
        f"""\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0

        [project]
        name = "node-wire-{dist}"
        version = "1.0.0"
        description = "Node Wire connector — {connector_id} (OpenAPI-generated)"
        requires-python = ">=3.11"
        license = "Apache-2.0"
        authors = [{{ name = "AOT Technologies", email = "opensource@aot-technologies.com" }}]

        dependencies = [
            "node-wire-runtime>=1.0.0",
            "httpx[http2]>=0.27.0,<0.28.0",
        ]

        [project.optional-dependencies]
        test = [
            "pytest>=8.0.0",
            "polyfactory>=2.16.0",
        ]

        [project.entry-points."node_wire.connectors"]
        {connector_id} = "node_wire_{connector_id}.logic"

        [build-system]
        requires = ["setuptools>=69.0.0", "cython>=3.0", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        where = ["../../../src"]
        include = ["node_wire_{connector_id}*"]

        [tool.pytest.ini_options]
        testpaths = ["tests"]
        """
    )


def generate_package_setup(connector_id: str) -> str:
    _validate_connector_id(connector_id)
    return textwrap.dedent(
        f"""\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0
        import glob
        import os

        from Cython.Build import cythonize
        from setuptools import setup
        from setuptools.command.build_ext import build_ext as _BuildExt
        from setuptools.command.build_py import build_py as _BuildPy


        class NoPyBuild(_BuildPy):
            def find_package_modules(self, package, package_dir):
                return []


        class ParallelBuildExt(_BuildExt):
            \"\"\"Compile extension modules with one compiler job per core.\"\"\"

            def finalize_options(self):
                super().finalize_options()
                if self.parallel is None:
                    self.parallel = os.cpu_count() or 1


        src_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../src/node_wire_{connector_id}"))
        py_files = glob.glob(os.path.join(src_root, "**", "*.py"), recursive=True)

        # Guarded so Cython's process pool can re-import this file on macOS and Windows.
        if __name__ == "__main__":
            setup(
                cmdclass={{"build_py": NoPyBuild, "build_ext": ParallelBuildExt}},
                ext_modules=cythonize(
                    py_files,
                    nthreads=os.cpu_count() or 1,
                    compiler_directives={{"language_level": "3"}},
                    build_dir="build",
                    annotate=False,
                ),
            )
        """
    )


def generate_model_tests(connector_id: str, result: DeriveResult) -> str:
    _validate_connector_id(connector_id)
    lines = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "import json",
        "",
        "from polyfactory.factories.pydantic_factory import ModelFactory",
        "",
        f"from node_wire_{connector_id} import schema as sch",
        "",
    ]
    for a in result.actions:
        in_name = _pascal(a.name) + "Input"
        lines += [
            f"def test_{a.name}_input_roundtrip() -> None:",
            "    class _F(ModelFactory):",
            f"        __model__ = sch.{in_name}",
            "    inst = _F.build()",
            "    data = inst.model_dump(by_alias=True)",
            f"    again = sch.{in_name}.model_validate(data)",
            f"    assert again.action == {a.name!r}",
            "",
        ]
        if a.examples.get("request") is not None and a.body_schema is not None:
            # Build a payload that satisfies required path/query/header fields so
            # the example→model gate does not abort on otherwise-valid specs.
            payload_bits = [f"'action': {a.name!r}", "'body': example"]
            for p in a.params:
                if not p.required:
                    continue
                payload_bits.append(f"{p.field_name!r}: {json.dumps(_example_placeholder(p))}")
            payload_expr = "{" + ", ".join(payload_bits) + "}"
            lines += [
                f"def test_{a.name}_example_parses() -> None:",
                f"    example = {json.dumps(a.examples['request'])}",
                f"    payload = {payload_expr}",
                f"    sch.{in_name}.model_validate(payload)",
                "",
            ]
    return "\n".join(lines)


def generate_package_readme(connector_id: str, result: DeriveResult) -> str:
    """Package README: what this connector is, and the credential contract it expects.

    The hand-written connectors each ship one. For generated packages the auth
    section matters most — the host has to know which secret to set and that
    nothing refreshes it, and that has until now only been visible in
    ``report.json`` and a ``sample.env`` comment.
    """
    _validate_connector_id(connector_id)
    plan = result.auth_plan
    lines = [
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "#",
        "# SPDX-License-Identifier: Apache-2.0",
        "",
        f"# {connector_id} connector (generated)",
        "",
        "> **Generated by** `nw-connector-builder` from an OpenAPI document — do not hand-edit.",
        f"> **Connector ID:** `{connector_id}`",
        f"> **Base URL:** `{result.default_base_url}`",
        f"> **Source:** `src/node_wire_{connector_id}/`",
        "",
        "## Actions",
        "",
        "| Action | Method | Path |",
        "| --- | --- | --- |",
    ]
    for a in result.actions:
        lines.append(f"| `{a.name}` | {a.method} | `{a.path}` |")
    lines += ["", "## Authentication", ""]

    if plan.tier == "host_supplied":
        lines += [
            f"**Host-supplied credential.** Node Wire presents `{plan.secret_key}` as an",
            "`Authorization: Bearer` header and never obtains, refreshes, or detects the",
            f"expiry of it — scheme `{plan.scheme_name}` in the source spec is an OAuth2 /",
            "OpenID Connect scheme, and the host application owns acquiring and rotating",
            "the token entirely out-of-band. A stale token surfaces as a plain `401`.",
        ]
    elif plan.provider in ("none", ""):
        lines.append("This connector's operations are anonymous — no credential is configured.")
    else:
        lines += [
            f"Provider `{plan.provider}`, resolved from `{plan.secret_key}` via the",
            "configured `SecretProvider`.",
        ]

    if plan.notes:
        lines += ["", "Build notes:", ""]
        lines.extend(f"- {note}" for note in plan.notes)

    if result.extra_auth_plans:
        lines += [
            "",
            "Some operations use a non-default scheme, emitted under `auth_schemes:` in",
            "`config/connectors.yaml`:",
            "",
        ]
        for name, extra in result.extra_auth_plans.items():
            lines.append(f"- `{name}` → `{extra.secret_key}` ({extra.provider})")

    lines += [
        "",
        "### Storing credentials per tenant",
        "",
        "`logic.py` calls `declare_secret_shape()` at import time, so this connector's",
        "secrets can be written through the config store per tenant/config even under",
        "`NW_SECRET_SHAPE_POLICY=enforce`. Without that declaration the store refuses",
        "credentials for connectors it does not recognise.",
        "",
        "## Provenance",
        "",
        f"See `packages/connectors/{connector_id}/report.json` for the source spec, the",
        "operations that were generated, and anything soft-dropped during the build.",
        "",
    ]
    return "\n".join(lines)


def write_staging(
    staging: Path,
    connector_id: str,
    result: DeriveResult,
    report: dict[str, Any],
) -> None:
    _validate_connector_id(connector_id)
    src_pkg = staging / "src" / f"node_wire_{connector_id}"
    pkg = staging / "packages" / "connectors" / connector_id
    tests = pkg / "tests"
    fixtures = tests / "fixtures"
    src_pkg.mkdir(parents=True, exist_ok=True)
    tests.mkdir(parents=True, exist_ok=True)
    fixtures.mkdir(parents=True, exist_ok=True)

    (src_pkg / "__init__.py").write_text(generate_init_module(connector_id), encoding="utf-8")
    (src_pkg / "schema.py").write_text(
        generate_schema_module(connector_id, result), encoding="utf-8"
    )
    (src_pkg / "logic.py").write_text(generate_logic_module(connector_id, result), encoding="utf-8")
    (src_pkg / "README.md").write_text(
        generate_package_readme(connector_id, result), encoding="utf-8"
    )
    (pkg / "pyproject.toml").write_text(generate_package_pyproject(connector_id), encoding="utf-8")
    (pkg / "setup.py").write_text(generate_package_setup(connector_id), encoding="utf-8")
    (tests / f"test_{connector_id}_models.py").write_text(
        generate_model_tests(connector_id, result), encoding="utf-8"
    )
    (tests / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    logger.info("Wrote staging tree under %s", staging)


# REUSE-IgnoreEnd
