#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

"""Remove everything ``nw gen-all`` / ``gen-mcp`` / ``gen-stacklok`` generated for a connector.

The next run of any of them then starts from scratch: no reused scope, connector, wheels or
output project.

Removed, per connector id (``slack_web`` → ``slack-web`` in project names):
  - src/node_wire_<id>/ and its .egg-info           the generated connector
  - packages/connectors/<id>/                       its package, wheels and build report
  - nw-mcp-builder/out/<id-hyphen>-nw-mcp/          the node-wire MCP host
  - nw-stacklok-builder/out/<server>-mcp/           every stacklok server built on the connector
  - nw-stacklok-builder/scoping/<id>/               the saved AI scope and its intermediates
  - nw-stacklok-builder/specs/<id>.openapi.json     the prepared spec
  - the connector's wiring in config/connectors.yaml, sample.env and scripts/build-packages.sh,
    but only where it isn't committed: committed wiring is left as it is.

Refuses to touch a hand-written connector (src/node_wire_<id>/logic.py without the generator's
marker) or connector files tracked by git. Shared runtime/bindings wheels, Docker images and
ToolHive workloads are left alone.

Usage:
  uv run python scripts/reset_connector.py slack_web [ms_teams ...] [--dry-run] [--yes]
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess  # nosec B404  # fixed git argv, no shell
import sys
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
CONNECTOR_ID = re.compile(r"[a-z][a-z0-9_]*")
GENERATED_MARKER = "Generated by nw-connector-builder"  # nw_connector_builder.promote
ALLOW_LIST = re.compile(r"^(NW_ALLOWED_CONNECTORS=)(.*)$")
HOST_SUPPLIED_NOTE = "host-supplied credential"  # nw_connector_builder.wire


class ResetError(Exception):
    pass


@dataclass
class Plan:
    paths: list[Path] = field(default_factory=list)
    tracked: list[str] = field(default_factory=list)  # git-tracked files among ``paths``
    unwire: list[str] = field(default_factory=list)  # human-readable wiring edits
    edits: dict[Path, str] = field(default_factory=dict)  # file -> new content


def _git(root: Path, *args: str) -> str | None:
    try:
        proc = subprocess.run(  # nosec B603 B607  # fixed git argv
            ["git", *args], cwd=root, capture_output=True, text=True, check=False
        )
    except FileNotFoundError:
        return None
    return proc.stdout if proc.returncode == 0 else None


def _tracked(root: Path, path: Path) -> list[str]:
    out = _git(root, "ls-files", "--", str(path.relative_to(root)))
    return out.split() if out else []


def _committed(root: Path, rel: str) -> str:
    """``rel`` as of HEAD, or "" when it isn't committed."""
    return _git(root, "show", f"HEAD:{rel}") or ""


def _read(path: Path, pending: Mapping[Path, str]) -> str:
    """``path`` as it will be once the edits already planned for earlier ids are applied."""
    return pending[path] if path in pending else path.read_text(encoding="utf-8")


def _connector_ids_of(project: Path) -> set[str]:
    try:
        doc = yaml.safe_load((project / "config" / "connectors.yaml").read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return set()
    connectors = doc.get("connectors") if isinstance(doc, dict) else None
    return set(connectors) if isinstance(connectors, dict) else set()


def _check_generated(root: Path, connector_id: str) -> None:
    src = root / "src" / f"node_wire_{connector_id}"
    logic = src / "logic.py"
    if logic.is_file() and GENERATED_MARKER not in logic.read_text(encoding="utf-8")[:512]:
        raise ResetError(f"{src} is a hand-written connector; not removing it")
    for path in (src, root / "packages" / "connectors" / connector_id):
        if path.exists() and _tracked(root, path):
            raise ResetError(f"{path} has files tracked by git; not removing it")


def _secret_keys(entry: object) -> set[str]:
    """Every ``secret_key`` in a connectors.yaml entry (its default and named auth schemes)."""
    if not isinstance(entry, dict):
        return set()
    blocks = [entry.get("auth"), *(entry.get("auth_schemes") or {}).values()]
    return {b["secret_key"] for b in blocks if isinstance(b, dict) and b.get("secret_key")}


def _unwire_connectors_yaml(
    root: Path, connector_id: str, plan: Plan, pending: Mapping[Path, str]
) -> set[str]:
    """Drop an uncommitted connectors.yaml entry; returns its secret keys."""
    path = root / "config" / "connectors.yaml"
    if not path.is_file():
        return set()
    text = _read(path, pending)
    current = yaml.safe_load(text) or {}
    entry = (current.get("connectors") or {}).get(connector_id)
    committed = yaml.safe_load(_committed(root, "config/connectors.yaml")) or {}
    if entry is None or connector_id in (committed.get("connectors") or {}):
        return set()

    from ruamel.yaml import YAML  # comment-preserving, like nw_connector_builder.wire

    ruamel = YAML()
    ruamel.preserve_quotes = True
    data = ruamel.load(text)
    del data["connectors"][connector_id]
    from io import StringIO

    out = StringIO()
    ruamel.dump(data, out)
    plan.edits[path] = out.getvalue()
    plan.unwire.append(f"config/connectors.yaml: the {connector_id} entry")
    return _secret_keys(entry)


def _unwire_sample_env(
    root: Path, connector_id: str, secret_keys: set[str], plan: Plan, pending: Mapping[Path, str]
) -> None:
    path = root / "sample.env"
    if not path.is_file():
        return
    committed = _committed(root, "sample.env")
    committed_keys = set(re.findall(r"^([A-Z0-9_]+)=", committed, flags=re.MULTILINE))
    committed_allowed = next(
        (m.group(2).split(",") for m in map(ALLOW_LIST.match, committed.splitlines()) if m), []
    )
    drop_keys = secret_keys - committed_keys

    lines, changed = [], False
    for line in _read(path, pending).splitlines():
        allow = ALLOW_LIST.match(line)
        key = re.match(r"^([A-Z0-9_]+)=", line)
        if allow and connector_id not in committed_allowed:
            parts = [p for p in allow.group(2).split(",") if p.strip() != connector_id]
            if len(parts) != len(allow.group(2).split(",")):
                line, changed = allow.group(1) + ",".join(parts), True
        elif key and key.group(1) in drop_keys:
            if lines and lines[-1].startswith(f"# {key.group(1)}: {HOST_SUPPLIED_NOTE}"):
                lines.pop()
            changed = True
            continue
        lines.append(line)
    if changed:
        plan.edits[path] = "\n".join(lines) + "\n"
        plan.unwire.append(f"sample.env: {connector_id} in NW_ALLOWED_CONNECTORS and its secrets")


def _unwire_build_packages(
    root: Path, connector_id: str, plan: Plan, pending: Mapping[Path, str]
) -> None:
    rel = "scripts/build-packages.sh"
    path = root / rel
    line = f"  packages/connectors/{connector_id}"
    if not path.is_file() or line in _committed(root, rel).splitlines():
        return
    text = _read(path, pending)
    if line + "\n" in text:
        plan.edits[path] = text.replace(line + "\n", "", 1)
        plan.unwire.append(f"{rel}: packages/connectors/{connector_id} in ALL_PACKAGES")


def plan_reset(root: Path, connector_id: str, pending: Mapping[Path, str] | None = None) -> Plan:
    """What resetting ``connector_id`` removes and rewrites.

    ``pending`` holds the file edits already planned for other ids, so the wiring edits of
    several ids build on each other instead of each rewriting the original file.
    """
    pending = pending or {}
    if not CONNECTOR_ID.fullmatch(connector_id):
        raise ResetError(f"invalid connector id {connector_id!r} (e.g. slack_web)")
    _check_generated(root, connector_id)
    plan = Plan()
    hyphen = connector_id.replace("_", "-")
    stacklok_out = root / "nw-stacklok-builder" / "out"
    candidates = [
        root / "src" / f"node_wire_{connector_id}",
        root / "src" / f"node_wire_{connector_id}.egg-info",
        root / "packages" / "connectors" / connector_id,
        root / "nw-mcp-builder" / "out" / f"{hyphen}-nw-mcp",
        *(
            project
            for project in sorted(stacklok_out.glob("*-mcp") if stacklok_out.is_dir() else [])
            if connector_id in _connector_ids_of(project)
        ),
        root / "nw-stacklok-builder" / "scoping" / connector_id,
        root / "nw-stacklok-builder" / "specs" / f"{connector_id}.openapi.json",
    ]
    # Leftovers of an interrupted promote (nw_connector_builder.promote).
    for base in (candidates[0], candidates[2]):
        candidates += [base.with_name(base.name + suffix) for suffix in (".promoting", ".bak")]
    plan.paths = [path for path in candidates if path.exists()]
    for path in plan.paths:
        plan.tracked += _tracked(root, path)

    secret_keys = _unwire_connectors_yaml(root, connector_id, plan, pending)
    _unwire_sample_env(root, connector_id, secret_keys, plan, pending)
    _unwire_build_packages(root, connector_id, plan, pending)
    return plan


def apply(plan: Plan) -> None:
    for path in plan.paths:
        if path.is_dir() and not path.is_symlink():
            shutil.rmtree(path)
        else:
            path.unlink()
    for path, text in plan.edits.items():
        path.write_text(text, encoding="utf-8")


def _show(root: Path, connector_id: str, plan: Plan) -> None:
    print(f"{connector_id}:")
    if not plan.paths and not plan.unwire:
        print("  nothing generated; already reset")
    for path in plan.paths:
        print(f"  remove  {path.relative_to(root)}")
    for edit in plan.unwire:
        print(f"  unwire  {edit}")
    for rel in plan.tracked:
        print(
            f"  note    {rel} is tracked by git; it will show as deleted (git restore brings it back)"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("connector_ids", nargs="+", metavar="CONNECTOR_ID")
    parser.add_argument("--dry-run", action="store_true", help="show what would be removed")
    parser.add_argument("--yes", "-y", action="store_true", help="don't ask for confirmation")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root.resolve()

    plans: dict[str, Plan] = {}
    pending: dict[Path, str] = {}
    try:
        for connector_id in dict.fromkeys(args.connector_ids):
            plans[connector_id] = plan_reset(root, connector_id, pending)
            pending.update(plans[connector_id].edits)
    except ResetError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    for connector_id, plan in plans.items():
        _show(root, connector_id, plan)
    if args.dry_run or not any(p.paths or p.edits for p in plans.values()):
        return 0
    if not args.yes:
        if not sys.stdin.isatty():
            print("error: no terminal to confirm; pass --yes", file=sys.stderr)
            return 1
        if input("Proceed? [y/N] ").strip().lower() not in ("y", "yes"):
            print("Nothing removed.")
            return 1
    for plan in plans.values():
        apply(plan)
    print("Done. The next gen-all / gen-mcp / gen-stacklok run starts from scratch.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
